/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoiceConfigRouteImport } from './routes/api/voice-config'
import { Route as ApiVocaConfigRouteImport } from './routes/api/voca-config'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceConfigRoute = ApiVoiceConfigRouteImport.update({
  id: '/api/voice-config',
  path: '/api/voice-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVocaConfigRoute = ApiVocaConfigRouteImport.update({
  id: '/api/voca-config',
  path: '/api/voca-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/voca-config': typeof ApiVocaConfigRoute
  '/api/voice-config': typeof ApiVoiceConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/voca-config': typeof ApiVocaConfigRoute
  '/api/voice-config': typeof ApiVoiceConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/voca-config': typeof ApiVocaConfigRoute
  '/api/voice-config': typeof ApiVoiceConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/stt'
    | '/api/voca-config'
    | '/api/voice-config'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/stt' | '/api/voca-config' | '/api/voice-config'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/stt'
    | '/api/voca-config'
    | '/api/voice-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiVocaConfigRoute: typeof ApiVocaConfigRoute
  ApiVoiceConfigRoute: typeof ApiVoiceConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-config': {
      id: '/api/voice-config'
      path: '/api/voice-config'
      fullPath: '/api/voice-config'
      preLoaderRoute: typeof ApiVoiceConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voca-config': {
      id: '/api/voca-config'
      path: '/api/voca-config'
      fullPath: '/api/voca-config'
      preLoaderRoute: typeof ApiVocaConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSttRoute: ApiSttRoute,
  ApiVocaConfigRoute: ApiVocaConfigRoute,
  ApiVoiceConfigRoute: ApiVoiceConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
